In [1]:
import voronoi_cgal
import numpy as np

points = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 1]])
weights = np.array([1.0, 0.5, 0.5, 0.5, 1.0])

vertices, edges = voronoi_cgal.compute_voronoi(points, weights)
print("Voronoi Vertices:\n", vertices)
print("Edges:\n", edges)


Voronoi Vertices:
 [[ 0.875 -0.25   0.875]
 [-0.25   0.875  0.875]
 [ 0.875  0.875 -0.25 ]]
Edges:
 [[0 1]
 [0 2]
 [1 2]]
